import type { Metadata } from "next";
//import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "./StoreProvider";

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SAM QUEEN | DEVELOPER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${montserrat.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
